 docker-registry-web:
   image: hyper/docker-registry-web
   ports:
     - 80:8080
   links:
     - registry
   environment:
    REGISTRY_HOST: registry
    REGISTRY_PORT: 5000

 registry:
   image: registry:2
   ports:
     - 5000:5000
   environment:
     REGISTRY_STORAGE_DELETE_ENABLED: 'true'
     REGISTRY_STORAGE: 's3'
     REGISTRY_STORAGE_S3_REGION: 'ap-northeast-1'
     REGISTRY_STORAGE_S3_BUCKET: 'your_bucket'

 jenkins:
   image: atomitech/kiq-jenkins
   ports:
     - 8080:8080
   volumes:
     - ./jenkins:/var/jenkins_home

 jupyter:
   image: jupyter/notebook
   ports:
     - 8888:8888
   volumes:
     - ./jupyter:/notebooks
